---

- name: Global Git config
  template:
    src: git.config.j2
    dest: "{{ user.home }}/.gitconfig"
    owner: "{{ user.username }}"
    mode: "0644"
  with_items: users

- name: Global Git ignore
  template:
    src: git.ignore.j2
    dest: "{{ user.home }}/.gitignore"
    owner: "{{ user.username }}"
    mode: "0644"
  with_items: users