---

- name: Global Git config
  template:
    src: git.config.j2
    dest: "/Users/joao/.gitconfig"
    owner: "joao"
    mode: "0644"

- name: Global Git ignore
  template:
    src: git.ignore.j2
    dest: "/Users/joao/.gitignore"
    owner: "joao"
    mode: "0644"