---

#
# Install Homebrew
#
#- name: Check Homebrew is installed
#  stat: path=/usr/local/bin/brew
#  register: brew_installed
#
#- name: Install Homebrew
#  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
#  when: brew_installed.stat.exists == false
#  sudo: yes

#
# Updates and Upgrades
#
 - name: Update and Upgrade all
   homebrew:
     update_homebrew: yes
     upgrade_all: yes

 - name: Tap that...
   homebrew_tap:
     tap: "{{ item }}"
     state: present
   with_items: homebrew_taps

#
# Install Packages
#
 - name: Install packages
   homebrew:
     name: "{{ item.name }}"
     state: latest
     install_options: "{{ item.install_options|default() }}"
   with_items: homebrew_packages
